# Generated by Django 3.2.4 on 2021-06-07 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserapikey',
            name='user_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apikey', to=settings.AUTH_USER_MODEL),
        ),
    ]
